name: dokedu

services:
  postgres:
    image: postgres:17-alpine
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dokedu-postgres-data:/var/lib/postgresql/data

volumes:
  dokedu-postgres-data: